name: Bug Report
description: Report a problem with TypedJS
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: input
    id: version
    attributes:
      label: TypedJS version
      description: Output of `typedjs --version` or the package.json version
      placeholder: 0.2.2
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      description: Output of `node -v`
      placeholder: v20.11.1
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Windows
        - Linux
        - Other (please specify below)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: Provide a minimal code sample or steps to reproduce.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or stack trace
      description: Paste any relevant logs or stack traces.
      render: shell
    validations:
      required: false
