name: Feature Request
description: Suggest an idea for TypedJS
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve TypedJS.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve? Why is it needed?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior or API you want.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, examples, or screenshots.
    validations:
      required: false
